//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.5472
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;


namespace GPX
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.garmin.com/xmlschemas/TrackPointExtension/v1")]
    [System.Xml.Serialization.XmlRootAttribute("TrackPointExtension", Namespace = "http://www.garmin.com/xmlschemas/TrackPointExtension/v1", IsNullable = false)]
    public partial class TrackPointExtension_t
    {

        private double atempField;

        private bool atempFieldSpecified;

        private double wtempField;

        private bool wtempFieldSpecified;

        private double depthField;

        private bool depthFieldSpecified;

        private byte hrField;

        private bool hrFieldSpecified;

        private byte cadField;

        private bool cadFieldSpecified;

        private Extensions_t extensionsField;

        /// <remarks/>
        public double atemp
        {
            get
            {
                return this.atempField;
            }
            set
            {
                this.atempField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool atempSpecified
        {
            get
            {
                return this.atempFieldSpecified;
            }
            set
            {
                this.atempFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double wtemp
        {
            get
            {
                return this.wtempField;
            }
            set
            {
                this.wtempField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wtempSpecified
        {
            get
            {
                return this.wtempFieldSpecified;
            }
            set
            {
                this.wtempFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double depth
        {
            get
            {
                return this.depthField;
            }
            set
            {
                this.depthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool depthSpecified
        {
            get
            {
                return this.depthFieldSpecified;
            }
            set
            {
                this.depthFieldSpecified = value;
            }
        }

        /// <remarks/>
        public byte hr
        {
            get
            {
                return this.hrField;
            }
            set
            {
                this.hrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hrSpecified
        {
            get
            {
                return this.hrFieldSpecified;
            }
            set
            {
                this.hrFieldSpecified = value;
            }
        }

        /// <remarks/>
        public byte cad
        {
            get
            {
                return this.cadField;
            }
            set
            {
                this.cadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cadSpecified
        {
            get
            {
                return this.cadFieldSpecified;
            }
            set
            {
                this.cadFieldSpecified = value;
            }
        }

        /// <remarks/>
        public Extensions_t Extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
    }

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.garmin.com/xmlschemas/TrackPointExtension/v1")]
    //public partial class Extensions_t
    //{
    //    //private TrackPointExtension_t field;
    //    //[System.Xml.Serialization.XmlAnyElementAttribute()]
    //    //public TrackPointExtension_t Any
    //    //{
    //    //    get { return field; }
    //    //    set { field = value; }
    //    //}


    //    private System.Xml.XmlElement[] anyField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlAnyElementAttribute()]
    //    public System.Xml.XmlElement[] Any
    //    {
    //        get
    //        {
    //            return this.anyField;
    //        }
    //        set
    //        {
    //            this.anyField = value;
    //        }
    //    }
    //}
}